# Generated by Django 4.0 on 2022-10-03 21:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('timestamp', models.DateTimeField(auto_created=True, verbose_name='Time of creation.')),
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, verbose_name='The trade type.')),
                ('symbol', models.CharField(max_length=6, verbose_name='The stock symbol.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='The price of one share.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.user', to_field='id', verbose_name='Deal owner.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
