# Generated by Django 4.0 on 2022-10-07 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trades", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade",
                to="users.user",
                to_field="id",
                verbose_name="Deal owner.",
            ),
        ),
    ]
