# Generated by Django 4.0 on 2022-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('type', 'symbol', 'price', 'timestamp'), name='unique_trades'),
        ),
    ]
