# Generated by Django 4.0 on 2022-10-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_unique_trades'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trade',
            name='unique_trades',
        ),
    ]
