# Generated by Django 4.0 on 2022-10-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_remove_trade_unique_trades'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.UniqueConstraint(fields=('type', 'symbol', 'price', 'timestamp'), name='unique_trades'),
        ),
    ]
