version: '3.8'

services:
  db:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ../app
    restart: always
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn app.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
volumes:
  postgres_data:
  static_value:
  media_value: